version: "3.9"

services:

  authservice:
    build:
      context: ./backend/authService
    image: hv-authservice:latest
    environment:
      PORT: 3001
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_URLS: ${CLIENT_URLS}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    ports:
      - "3001:3001"

  adminservice:
    build:
      context: ./backend
      dockerfile: adminService/Dockerfile
    image: hv-adminservice:latest
    environment:
      PORT: 3003
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_URLS: ${CLIENT_URLS}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    ports:
      - "3003:3003"

  chatservice:
    build:
       context: ./backend
       dockerfile: chatService/Dockerfile
    image: hv-chatservice:latest
    environment:
      PORT: 3004
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_URLS: ${CLIENT_URLS}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    ports:
      - "3004:3004"

  streamingservice:
    build:
      context: ./backend
      dockerfile: streamingService/Dockerfile
    image: hv-streamingservice:latest
    environment:
      PORT: 3002
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_URLS: ${CLIENT_URLS}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_CDN_URL: ${AWS_CDN_URL}
      STREAMING_PUBLIC_URL: ${STREAMING_PUBLIC_URL}
    ports:
      - "3002:3002"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_AUTH_API_URL: http://k8s-hvapp-authserv-390a110ab7-cbf658734114d926.elb.ap-south-2.amazonaws.com:3001/api
      
        REACT_APP_STREAMING_API_URL: http://k8s-hvapp-streamin-761585a338-32c0d72d8081f784.elb.ap-south-2.amazonaws.com:3002/api
      
        REACT_APP_STREAMING_PUBLIC_URL: http://k8s-hvapp-streamin-761585a338-32c0d72d8081f784.elb.ap-south-2.amazonaws.com:3002
      
        REACT_APP_ADMIN_API_URL: http://k8s-hvapp-adminser-10f3822b7e-fed92cceb0a00f91.elb.ap-south-2.amazonaws.com:3003/api/admin
      
        REACT_APP_CHAT_API_URL: http://k8s-hvapp-chatserv-0752b84d17-5819c23091f9f12c.elb.ap-south-2.amazonaws.com:3004/api/chat
      
        REACT_APP_CHAT_SOCKET_URL: http://k8s-hvapp-chatserv-0752b84d17-5819c23091f9f12c.elb.ap-south-2.amazonaws.com:3004
    image: hv-frontend:latest
    depends_on:
      - authservice
      - adminservice
      - chatservice
      - streamingservice
    ports:
      - "3000:80"
